Repository sky-ecosystem/sky-governance-portal, pull requests merged in 2025-06, with the labels that each got.

#10 Main -> development
  modules/executive/api/fetchExecutives.ts
  pages/index.tsx
Labels: ready for review

#2 Pb/subgraph updates
  modules/gql/gql.constants.ts
Labels: ready for review, needs QA

#12 Update Subgraph URLs, Implement Poll Cache Expiry
  modules/cache/cache.ts
  modules/gql/gql.constants.ts
  modules/web3/constants/networks.ts
  pages/api/cache/info.ts
  pages/api/cache/invalidate.ts
  pages/dashboard/index.tsx
  pages/delegates/index.tsx
  pages/polling/review.tsx
Labels: ready for review, needs QA, release PR

#13 Handle missing gasless tx chainId
  modules/web3/stores/transactions.ts
Labels: ready for review, needs QA

#1 Update org references
  modules/delegates/api/getDelegatesRepositoryInfo.ts
  modules/executive/api/fetchExecutives.ts
  modules/polling/polling.constants.ts
  scripts/fetchTags.mjs
Labels: ready for review, do not merge

#18 Add API endpoint to retrieve paginated polls with tally data
  pages/api/executive/hat.ts
  pages/api/polling/all-polls-with-tally.ts
Labels: ready for review
